name: Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  # ЗАДАНИЕ 3.2: Этап тестирования
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install and Test Frontend
        # Переходим в папку 3.1, устанавливаем зависимости и запускаем тесты
        run: |
          cd 3.1/example-frontend
          npm install
          npm test -- --watchAll=false

  # ЗАДАНИЕ 3.1: Сборка и Пуш (запустится только если тесты прошли)
  build_and_push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./3.1/example-backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-backend:latest

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./3.1/example-frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-frontend:latest
